### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jferragut** [jferragut/flask-microservices-boilerplate#5]
This issue represents the tasks that we would like accomplished for the project at the current time. If we are taking control of a task, or adding one here, there should be an associated issue card to track what is being done.

- [ ] Update documentation for each of the functionalities #4 
- [ ] Update bash install script for conditional logic. (Must ask if user wants a specific installer set up and respond to user input.)
- [ ] Setup boilerplate to deploy on Heroku via script #3 
- [ ] Setup boilerplate to work with Netlify
- [ ] Configure Database example to work with Google Firebase database storage #2 
- [ ] Configure Database example to work with AWS database storage

**Comment by jferragut** [comment]
@all-contributors please add @jferragut for infrastructure, tests, ideas and code

**Comment by jferragut** [comment]
@all-contributors please add @jferragut for infrastructure, tests and code

**Comment by jferragut** [comment]
@all-contributors please add @jferragut for infrastructure, tests and code
